# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Youri-Package-RPM-Updater
version:      0.4.1
version_from: lib/Youri/Package/RPM/Updater.pm
installdirs:  site
requires:
    DateTime:                      0
    LWP::UserAgent:                0
    RPM4:                          0
    SVN::Client:                   0
    Test::Exception:               0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
