--- #YAML:1.0
name:                Youri-Package-RPM-Updater
version:             0.4.4
abstract:            ~
license:             ~
author:              
    - Youri project <youri@zarb.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DateTime:                      0
    LWP::UserAgent:                0
    RPM4:                          0
    SVN::Client:                   0
    Test::Exception:               0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
